name: car_wash
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image:
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: 5.0.0
  collection:
  connectivity_plus:
  csslib:
  currency_symbols: ^0.0.1+2
  device_info_plus:
  dots_indicator:
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  file_picker: ^8.1.4
  firebase_messaging: any
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_html:
  flutter_local_notifications: ^18.0.1
  flutter_paypal: any
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.16
  flutter_widget_from_html_core: ^0.15.2
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  html: 0.15.4
  http: 1.2.2
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+18
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+1
  image_picker_linux: 0.2.1+1
  image_picker_macos: 0.2.1+1
  image_picker_platform_interface: 2.10.0
  image_picker_windows: 0.2.1+1
  intl:
  intl_phone_field:
  json_path: ^0.7.4
  lottie: ^3.2.0
  mime_type: ^1.0.1
  page_transition: 2.1.0
  path_provider: ^2.1.5
  path_provider_android: ^2.2.14
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  permission_handler: ^11.3.1
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.3.4
  shared_preferences_foundation: ^2.5.3
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  table_calendar:
  timeago:
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.2
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: ^3.1.3
  video_player: 2.9.2
  video_player_android: ^2.7.16
  video_player_avfoundation: ^2.6.4
  video_player_platform_interface: 6.2.3
  video_player_web: ^2.3.3
  wakelock_plus: ^1.2.8
  translator:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dependency_overrides:
  http: 1.2.2
  uuid: ^4.5.1
  win32: ^5.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  image: ^4.3.0
  lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/semibold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

