// Export pages
export '/pages/home_pages/home_main_page/home_main_page_widget.dart'
    show HomeMainPageWidget;
export '/pages/log_in_page/sign_in_page/sign_in_page_widget.dart'
    show SignInPageWidget;
export '/pages/splash_page/splash_page_widget.dart' show SplashPageWidget;
export '/pages/onboarding_page/onboarding_page_widget.dart'
    show OnboardingPageWidget;
export '/pages/log_in_page/sign_up_page/sign_up_page_widget.dart'
    show SignUpPageWidget;
export '/pages/log_in_page/forgot_password_page/forgot_password_page_widget.dart'
    show ForgotPasswordPageWidget;
export '/pages/log_in_page/verification_page/verification_page_widget.dart'
    show VerificationPageWidget;
export '/pages/log_in_page/reset_password_page/reset_password_page_widget.dart'
    show ResetPasswordPageWidget;
export '/pages/log_in_page/select_vehicle_type_page/select_vehicle_type_page_widget.dart'
    show SelectVehicleTypePageWidget;
export '/pages/log_in_page/car_details_page/car_details_page_widget.dart'
    show CarDetailsPageWidget;
export '/pages/home_pages/recommended_service_page/recommended_service_page_widget.dart'
    show RecommendedServicePageWidget;
export '/pages/home_pages/maintain_your_car_page/maintain_your_car_page_widget.dart'
    show MaintainYourCarPageWidget;
export '/pages/home_pages/all_car_details_page/all_car_details_page_widget.dart'
    show AllCarDetailsPageWidget;
export '/pages/home_pages/select_tme_date_page/select_tme_date_page_widget.dart'
    show SelectTmeDatePageWidget;
export '/pages/home_pages/checkout_page/checkout_page_widget.dart'
    show CheckoutPageWidget;
export '/pages/home_pages/payment_method_page/payment_method_page_widget.dart'
    show PaymentMethodPageWidget;
export '/pages/my_order_pages/my_order_detail_page/my_order_detail_page_widget.dart'
    show MyOrderDetailPageWidget;
export '/pages/profile_pages/my_profile_page/my_profile_page_widget.dart'
    show MyProfilePageWidget;
export '/pages/edit_profile_page/edit_profile_page_widget.dart'
    show EditProfilePageWidget;
export '/pages/profile_pages/address_page/address_page_widget.dart'
    show AddressPageWidget;
export '/pages/profile_pages/add_new_address_page/add_new_address_page_widget.dart'
    show AddNewAddressPageWidget;
export '/pages/profile_pages/my_cars_page/my_cars_page_widget.dart'
    show MyCarsPageWidget;
export '/pages/home_pages/banner_page/banner_page_widget.dart'
    show BannerPageWidget;
export '/pages/profile_pages/setting_page/setting_page_widget.dart'
    show SettingPageWidget;
export '/pages/profile_pages/about_us_page/about_us_page_widget.dart'
    show AboutUsPageWidget;
export '/pages/profile_pages/terms_condition_page/terms_condition_page_widget.dart'
    show TermsConditionPageWidget;
export '/pages/profile_pages/privacy_policy_page/privacy_policy_page_widget.dart'
    show PrivacyPolicyPageWidget;
export '/pages/profile_pages/edit_address_page/edit_address_page_widget.dart'
    show EditAddressPageWidget;
export '/pages/log_in_page/forgot_verification_page/forgot_verification_page_widget.dart'
    show ForgotVerificationPageWidget;
export '/pages/home_pages/change_address_page/change_address_page_widget.dart'
    show ChangeAddressPageWidget;
export '/pages/home_pages/my_coupon_page/my_coupon_page_widget.dart'
    show MyCouponPageWidget;
export '/pages/home_pages/payment_failed_page/payment_failed_page_widget.dart'
    show PaymentFailedPageWidget;
export '/pages/home_pages/payment_success_page/payment_success_page_widget.dart'
    show PaymentSuccessPageWidget;
export '/pages/home_pages/payment_gateway_page/payment_gateway_page_widget.dart'
    show PaymentGatewayPageWidget;
export '/pages/home_pages/select_tme_date_page_copy/select_tme_date_page_copy_widget.dart'
    show SelectTmeDatePageCopyWidget;
export '/pages/profile_pages/car_details_edit_page/car_details_edit_page_widget.dart'
    show CarDetailsEditPageWidget;
export '/pages/profile_pages/select_vehicle_type_edit_page/select_vehicle_type_edit_page_widget.dart'
    show SelectVehicleTypeEditPageWidget;
export '/pages/home_pages/my_order_confirm_page/my_order_confirm_page_widget.dart'
    show MyOrderConfirmPageWidget;
export '/pages/home_pages/checkout_page_copy/checkout_page_copy_widget.dart'
    show CheckoutPageCopyWidget;
export '/pages/home_pages/notification_page/notification_page_widget.dart'
    show NotificationPageWidget;
export '/pages/home_pages/payment_gateway_page_copy/payment_gateway_page_copy_widget.dart'
    show PaymentGatewayPageCopyWidget;
